ats:
  authentication:
    token:
  client:
    id:
  jobrun:
    history:
      directory: ./
      file: jobRunHistory.txt
  request:
    batch:
      size: 10
    endpoint:

cshr:
  api:
    service:
      department:
        findAll:
          endpoint: http://localhost:8080/department
      search:
        password: searchpassword
        username: searchusername
      vacancy:
        save:
          endpoint: http://localhost:8080/vacancy/save
          password: crudpassword
          username: crudusername
  ats:
    vendor:
      id: vendorId
  jobrun:
    audit:
      directory: ./
      basefilename: VacancyProcessor

spring:
  security:
    service:
      password: servicepassword
      username: serviceusername

server:
  port: 10080